services:
  - type: web
    name: aquaspot-web
    env: python
    region: oregon # or your preferred region
    plan: free # or starter/standard for better performance
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      # Add your secrets via Render dashboard:
      # - COPERNICUS_USERNAME
      # - COPERNICUS_PASSWORD
      # - SMTP_SERVER (optional)
      # - SMTP_PORT (optional)
      # - SMTP_USERNAME (optional)
      # - SMTP_PASSWORD (optional)
    autoDeploy: true
    healthCheckPath: /health
